import re, os

def replace_tags(text):
    text = re.sub('lex="([^"=]+)=', r'lex="\1', text)
    text = re.sub('lex="([^"_]+)_([^"_]+)" gr="([^",]+)',r'lex="\1\2" wordf="\1+\2" gr="\3,compos,', text)
    text = re.sub('lex="([^"_]+)_([^"_]+)_([^"_]+)" gr="([^",]+)', r'lex="\1\2\3" wordf="\1+\2+\3" gr="\4,compos,', text)
    text = re.sub('" />', '"/>', text)

    text = re.sub('gr="B(,|")', r'gr="A,comp\1', text)
    text = re.sub('gr="D(,|")', r'gr="ADV\1', text)
    text = re.sub('gr="G(,|")', r'gr="A,poss\1', text)
    text = re.sub('gr="H(,|")', r'gr="S,persn\1', text)
    text = re.sub('gr="I(,|")', r'gr="INTJ\1', text)
    text = re.sub('gr="J(,|")', r'gr="CONJ\1', text)
    text = re.sub('gr="K(,|")', r'gr="PR\1', text)
    text = re.sub('gr="N(,|")', r'gr="NUM\1', text)
    text = re.sub('gr="O(,|")', r'gr="ANUM\1', text)
    text = re.sub('gr="P(,|")', r'gr="PRO\1', text)
    text = re.sub('gr="U(,|")', r'gr="A,supr\1', text)
    text = re.sub('gr="X(,|")', r'gr="ADV,phras\1', text)
    text = re.sub('gr="Y(,|")', r'gr="INIT,abbr\1', text)
    text = re.sub('<w><ana lex="[^"]+" gr="Z"/>([^<]+)</w>', r'\1', text)

    text = re.sub(',g(,|")', r',gen\1', text)
    text = re.sub('([^V]),n(,|")', r'\1,nom\2', text)
    text = re.sub(',p(,|")', r',part\1', text)

    text = re.sub(',b(,|")', r',indic,act,praes,3p,sg\1', text)
    text = re.sub(',d(,|")', r',indic,act,praes,2p,sg\1', text)
    text = re.sub(',da(,|")', r',inf\1', text)
    text = re.sub(',des(,|")', r',ger\1', text)
    text = re.sub(',ge(,|")', r',imper,act,praes,2p,pl\1', text)
    text = re.sub(',gem(,|")', r',imper,act,praes,1p,pl\1', text)
    text = re.sub(',gu(,|")', r',imper,act,praes,3p\1', text)
    text = re.sub(',ks(,|")', r',cond,act,praes\1', text)
    text = re.sub(',ksid(,|")', r',cond,act,praes,2p,sg\1', text)
    text = re.sub(',ksid(,|")', r',cond,act,praes,3p,pl\1', text)
    text = re.sub(',ksime(,|")', r',cond,act,praes,1p,pl\1', text)
    text = re.sub(',ksin(,|")', r',cond,act,praes,1p,sg\1', text)
    text = re.sub(',ksite(,|")', r',cond,act,praes,2p,pl\1', text)
    text = re.sub(',ma(,|")', r',sup,act\1', text)
    text = re.sub(',maks(,|")', r',sup,act,tr\1', text)
    text = re.sub(',mas(,|")', r',sup,act,in\1', text)
    text = re.sub(',mast(,|")', r',sup,act,el\1', text)
    text = re.sub(',mata(,|")', r',sup,act,ab\1', text)
    text = re.sub(',me(,|")', r',indic,act,praes,1p,pl\1', text)
    text = re.sub('V,n(,|")', r'V,indic,act,praes,1p,sg\1', text)
    text = re.sub(',neg(,|")', r',neg\1', text)
    text = re.sub(',nud(,|")', r',partcp,act,praet\1', text)
    text = re.sub(',nuks(,|")', r',cond,act,praet\1', text)
    text = re.sub(',nuksid(,|")', r',cond,act,praet,\(2p,sg\|3p,pl\)\1', text)
    text = re.sub(',nuksime(,|")', r',cond,act,praet,1p,pl\1', text)
    text = re.sub(',nuksin(,|")', r',cond,act,praet,1p,sg\1', text)
    text = re.sub(',nuksite(,|")', r',cond,act,praet,2p,pl\1', text)
    text = re.sub(',nuvat(,|")', r',quot,act,praet\1', text)
    text = re.sub(',o(,|")', r',imper,act,praes,2p,sg\1', text)
    text = re.sub(',s(,|")', r',indic,act,praet,3p,sg\1', text)
    text = re.sub(',sid(,|")', r',indic,act,praet,\(2p,sg\|3p,pl\)\1', text)
    text = re.sub(',sime(,|")', r',indic,act,praet,1p,pl\1', text)
    text = re.sub(',sin(,|")', r',indic,act,praet,1p,sg\1', text)
    text = re.sub(',site(,|")', r',indic,act,praet,2p,pl\1', text)
    text = re.sub(',ta(,|")', r',indic,pass,praes,neg\1', text)
    text = re.sub(',tagu(,|")', r',imper,pass,praes\1', text)
    text = re.sub(',taks(,|")', r',cond,pass,praes\1', text)
    text = re.sub(',takse(,|")', r',indic,pass,praes\1', text)
    text = re.sub(',tama(,|")', r',sup,pass\1', text)
    text = re.sub(',tav(,|")', r',partcp,pass,praes\1', text)
    text = re.sub(',tavat(,|")', r',quot,pass,praes\1', text)
    text = re.sub(',te(,|")', r',indic,act,praes,2p,pl\1', text)
    text = re.sub(',ti(,|")', r',indic,pass,praet\1', text)
    text = re.sub(',tud(,|")', r',partcp,pass,praet\1', text)
    text = re.sub(',tuks(,|")', r',cond,pass,praet\1', text)
    text = re.sub(',tuvat(,|")', r',quot,pass,praet\1', text)
    text = re.sub(',v(,|")', r',partcp,act,praes\1', text)
    text = re.sub(',vad(,|")', r',indic,act,praes,3p,pl\1', text)
    text = re.sub(',vat(,|")', r',quot,act,praes\1', text)

    text = re.sub('(gr=".+?),\?"', r'\1"', text)

    text = re.sub(r'<ana([^>]+),\\\(2p,sg\\\|3p,pl\\\)"/>', r'<ana\1,2p,sg"/><ana\1,3p,pl"/>', text)
    text = re.sub(',+', ',', text)
    return text

for root, dir, files in os.walk(r'C:\Users\mjo\PycharmProjects\homeworks\rnc_taggers\texts\estonian\estonian_analyzed'):
    for file in files:
        fullpath = os.path.join(root, file)
        with open(fullpath, encoding='utf-8') as f:
            text = f.read()
        text = replace_tags(text)
        with open(fullpath, 'w', encoding='utf-8') as f:
            f.write(text)
